//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Administracion.ServicioWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiServicioSoap", Namespace="http://tempuri.org/")]
    public partial class MiServicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ParaPoderSerializarOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaPropiedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaPropiedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificaPropiedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarPropiedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParaPoderSerializarCAsaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParaPoderSerializarAptoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParaPoderSerializarComercioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPropiedadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarZonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarZonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarZonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarZonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListoPorDptoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarVisitasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiServicio() {
            this.Url = global::Administracion.Properties.Settings.Default.Administracion_ServicioWeb_MiServicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ParaPoderSerializarCompletedEventHandler ParaPoderSerializarCompleted;
        
        /// <remarks/>
        public event AltaPropiedadCompletedEventHandler AltaPropiedadCompleted;
        
        /// <remarks/>
        public event BajaPropiedadCompletedEventHandler BajaPropiedadCompleted;
        
        /// <remarks/>
        public event ModificaPropiedadCompletedEventHandler ModificaPropiedadCompleted;
        
        /// <remarks/>
        public event BuscarPropiedadCompletedEventHandler BuscarPropiedadCompleted;
        
        /// <remarks/>
        public event ParaPoderSerializarCAsaCompletedEventHandler ParaPoderSerializarCAsaCompleted;
        
        /// <remarks/>
        public event ParaPoderSerializarAptoCompletedEventHandler ParaPoderSerializarAptoCompleted;
        
        /// <remarks/>
        public event ParaPoderSerializarComercioCompletedEventHandler ParaPoderSerializarComercioCompleted;
        
        /// <remarks/>
        public event ListarPropiedadesCompletedEventHandler ListarPropiedadesCompleted;
        
        /// <remarks/>
        public event AgregarZonaCompletedEventHandler AgregarZonaCompleted;
        
        /// <remarks/>
        public event EliminarZonaCompletedEventHandler EliminarZonaCompleted;
        
        /// <remarks/>
        public event ModificarZonaCompletedEventHandler ModificarZonaCompleted;
        
        /// <remarks/>
        public event BuscarZonaCompletedEventHandler BuscarZonaCompleted;
        
        /// <remarks/>
        public event ListoCompletedEventHandler ListoCompleted;
        
        /// <remarks/>
        public event ListoPorDptoCompletedEventHandler ListoPorDptoCompleted;
        
        /// <remarks/>
        public event AgregarEmpleadoCompletedEventHandler AgregarEmpleadoCompleted;
        
        /// <remarks/>
        public event EliminarEmpleadoCompletedEventHandler EliminarEmpleadoCompleted;
        
        /// <remarks/>
        public event ModificarEmpleadoCompletedEventHandler ModificarEmpleadoCompleted;
        
        /// <remarks/>
        public event BuscarEmpleadoCompletedEventHandler BuscarEmpleadoCompleted;
        
        /// <remarks/>
        public event ListarVisitasCompletedEventHandler ListarVisitasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaPoderSerializar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ParaPoderSerializar(Casa unaCasa, Apto unApto, Comercio unComercio) {
            this.Invoke("ParaPoderSerializar", new object[] {
                        unaCasa,
                        unApto,
                        unComercio});
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAsync(Casa unaCasa, Apto unApto, Comercio unComercio) {
            this.ParaPoderSerializarAsync(unaCasa, unApto, unComercio, null);
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAsync(Casa unaCasa, Apto unApto, Comercio unComercio, object userState) {
            if ((this.ParaPoderSerializarOperationCompleted == null)) {
                this.ParaPoderSerializarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaPoderSerializarOperationCompleted);
            }
            this.InvokeAsync("ParaPoderSerializar", new object[] {
                        unaCasa,
                        unApto,
                        unComercio}, this.ParaPoderSerializarOperationCompleted, userState);
        }
        
        private void OnParaPoderSerializarOperationCompleted(object arg) {
            if ((this.ParaPoderSerializarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaPoderSerializarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaPropiedad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaPropiedad(Propiedad p) {
            this.Invoke("AltaPropiedad", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void AltaPropiedadAsync(Propiedad p) {
            this.AltaPropiedadAsync(p, null);
        }
        
        /// <remarks/>
        public void AltaPropiedadAsync(Propiedad p, object userState) {
            if ((this.AltaPropiedadOperationCompleted == null)) {
                this.AltaPropiedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaPropiedadOperationCompleted);
            }
            this.InvokeAsync("AltaPropiedad", new object[] {
                        p}, this.AltaPropiedadOperationCompleted, userState);
        }
        
        private void OnAltaPropiedadOperationCompleted(object arg) {
            if ((this.AltaPropiedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaPropiedadCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaPropiedad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaPropiedad(Propiedad p) {
            this.Invoke("BajaPropiedad", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void BajaPropiedadAsync(Propiedad p) {
            this.BajaPropiedadAsync(p, null);
        }
        
        /// <remarks/>
        public void BajaPropiedadAsync(Propiedad p, object userState) {
            if ((this.BajaPropiedadOperationCompleted == null)) {
                this.BajaPropiedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaPropiedadOperationCompleted);
            }
            this.InvokeAsync("BajaPropiedad", new object[] {
                        p}, this.BajaPropiedadOperationCompleted, userState);
        }
        
        private void OnBajaPropiedadOperationCompleted(object arg) {
            if ((this.BajaPropiedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaPropiedadCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificaPropiedad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificaPropiedad(Propiedad p) {
            this.Invoke("ModificaPropiedad", new object[] {
                        p});
        }
        
        /// <remarks/>
        public void ModificaPropiedadAsync(Propiedad p) {
            this.ModificaPropiedadAsync(p, null);
        }
        
        /// <remarks/>
        public void ModificaPropiedadAsync(Propiedad p, object userState) {
            if ((this.ModificaPropiedadOperationCompleted == null)) {
                this.ModificaPropiedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificaPropiedadOperationCompleted);
            }
            this.InvokeAsync("ModificaPropiedad", new object[] {
                        p}, this.ModificaPropiedadOperationCompleted, userState);
        }
        
        private void OnModificaPropiedadOperationCompleted(object arg) {
            if ((this.ModificaPropiedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificaPropiedadCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarPropiedad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Propiedad BuscarPropiedad(int pPadron) {
            object[] results = this.Invoke("BuscarPropiedad", new object[] {
                        pPadron});
            return ((Propiedad)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarPropiedadAsync(int pPadron) {
            this.BuscarPropiedadAsync(pPadron, null);
        }
        
        /// <remarks/>
        public void BuscarPropiedadAsync(int pPadron, object userState) {
            if ((this.BuscarPropiedadOperationCompleted == null)) {
                this.BuscarPropiedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarPropiedadOperationCompleted);
            }
            this.InvokeAsync("BuscarPropiedad", new object[] {
                        pPadron}, this.BuscarPropiedadOperationCompleted, userState);
        }
        
        private void OnBuscarPropiedadOperationCompleted(object arg) {
            if ((this.BuscarPropiedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarPropiedadCompleted(this, new BuscarPropiedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaPoderSerializarCAsa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Casa ParaPoderSerializarCAsa() {
            object[] results = this.Invoke("ParaPoderSerializarCAsa", new object[0]);
            return ((Casa)(results[0]));
        }
        
        /// <remarks/>
        public void ParaPoderSerializarCAsaAsync() {
            this.ParaPoderSerializarCAsaAsync(null);
        }
        
        /// <remarks/>
        public void ParaPoderSerializarCAsaAsync(object userState) {
            if ((this.ParaPoderSerializarCAsaOperationCompleted == null)) {
                this.ParaPoderSerializarCAsaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaPoderSerializarCAsaOperationCompleted);
            }
            this.InvokeAsync("ParaPoderSerializarCAsa", new object[0], this.ParaPoderSerializarCAsaOperationCompleted, userState);
        }
        
        private void OnParaPoderSerializarCAsaOperationCompleted(object arg) {
            if ((this.ParaPoderSerializarCAsaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaPoderSerializarCAsaCompleted(this, new ParaPoderSerializarCAsaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaPoderSerializarApto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Apto ParaPoderSerializarApto() {
            object[] results = this.Invoke("ParaPoderSerializarApto", new object[0]);
            return ((Apto)(results[0]));
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAptoAsync() {
            this.ParaPoderSerializarAptoAsync(null);
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAptoAsync(object userState) {
            if ((this.ParaPoderSerializarAptoOperationCompleted == null)) {
                this.ParaPoderSerializarAptoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaPoderSerializarAptoOperationCompleted);
            }
            this.InvokeAsync("ParaPoderSerializarApto", new object[0], this.ParaPoderSerializarAptoOperationCompleted, userState);
        }
        
        private void OnParaPoderSerializarAptoOperationCompleted(object arg) {
            if ((this.ParaPoderSerializarAptoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaPoderSerializarAptoCompleted(this, new ParaPoderSerializarAptoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaPoderSerializarComercio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Comercio ParaPoderSerializarComercio() {
            object[] results = this.Invoke("ParaPoderSerializarComercio", new object[0]);
            return ((Comercio)(results[0]));
        }
        
        /// <remarks/>
        public void ParaPoderSerializarComercioAsync() {
            this.ParaPoderSerializarComercioAsync(null);
        }
        
        /// <remarks/>
        public void ParaPoderSerializarComercioAsync(object userState) {
            if ((this.ParaPoderSerializarComercioOperationCompleted == null)) {
                this.ParaPoderSerializarComercioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaPoderSerializarComercioOperationCompleted);
            }
            this.InvokeAsync("ParaPoderSerializarComercio", new object[0], this.ParaPoderSerializarComercioOperationCompleted, userState);
        }
        
        private void OnParaPoderSerializarComercioOperationCompleted(object arg) {
            if ((this.ParaPoderSerializarComercioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaPoderSerializarComercioCompleted(this, new ParaPoderSerializarComercioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarPropiedades", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Propiedad[] ListarPropiedades() {
            object[] results = this.Invoke("ListarPropiedades", new object[0]);
            return ((Propiedad[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPropiedadesAsync() {
            this.ListarPropiedadesAsync(null);
        }
        
        /// <remarks/>
        public void ListarPropiedadesAsync(object userState) {
            if ((this.ListarPropiedadesOperationCompleted == null)) {
                this.ListarPropiedadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPropiedadesOperationCompleted);
            }
            this.InvokeAsync("ListarPropiedades", new object[0], this.ListarPropiedadesOperationCompleted, userState);
        }
        
        private void OnListarPropiedadesOperationCompleted(object arg) {
            if ((this.ListarPropiedadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPropiedadesCompleted(this, new ListarPropiedadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarZona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarZona(Zona unaZona) {
            this.Invoke("AgregarZona", new object[] {
                        unaZona});
        }
        
        /// <remarks/>
        public void AgregarZonaAsync(Zona unaZona) {
            this.AgregarZonaAsync(unaZona, null);
        }
        
        /// <remarks/>
        public void AgregarZonaAsync(Zona unaZona, object userState) {
            if ((this.AgregarZonaOperationCompleted == null)) {
                this.AgregarZonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarZonaOperationCompleted);
            }
            this.InvokeAsync("AgregarZona", new object[] {
                        unaZona}, this.AgregarZonaOperationCompleted, userState);
        }
        
        private void OnAgregarZonaOperationCompleted(object arg) {
            if ((this.AgregarZonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarZonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarZona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarZona(Zona unaZona) {
            this.Invoke("EliminarZona", new object[] {
                        unaZona});
        }
        
        /// <remarks/>
        public void EliminarZonaAsync(Zona unaZona) {
            this.EliminarZonaAsync(unaZona, null);
        }
        
        /// <remarks/>
        public void EliminarZonaAsync(Zona unaZona, object userState) {
            if ((this.EliminarZonaOperationCompleted == null)) {
                this.EliminarZonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarZonaOperationCompleted);
            }
            this.InvokeAsync("EliminarZona", new object[] {
                        unaZona}, this.EliminarZonaOperationCompleted, userState);
        }
        
        private void OnEliminarZonaOperationCompleted(object arg) {
            if ((this.EliminarZonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarZonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarZona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarZona(Zona unaZona) {
            this.Invoke("ModificarZona", new object[] {
                        unaZona});
        }
        
        /// <remarks/>
        public void ModificarZonaAsync(Zona unaZona) {
            this.ModificarZonaAsync(unaZona, null);
        }
        
        /// <remarks/>
        public void ModificarZonaAsync(Zona unaZona, object userState) {
            if ((this.ModificarZonaOperationCompleted == null)) {
                this.ModificarZonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarZonaOperationCompleted);
            }
            this.InvokeAsync("ModificarZona", new object[] {
                        unaZona}, this.ModificarZonaOperationCompleted, userState);
        }
        
        private void OnModificarZonaOperationCompleted(object arg) {
            if ((this.ModificarZonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarZonaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarZona", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Zona BuscarZona(string pLetra, string pAbrev) {
            object[] results = this.Invoke("BuscarZona", new object[] {
                        pLetra,
                        pAbrev});
            return ((Zona)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarZonaAsync(string pLetra, string pAbrev) {
            this.BuscarZonaAsync(pLetra, pAbrev, null);
        }
        
        /// <remarks/>
        public void BuscarZonaAsync(string pLetra, string pAbrev, object userState) {
            if ((this.BuscarZonaOperationCompleted == null)) {
                this.BuscarZonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarZonaOperationCompleted);
            }
            this.InvokeAsync("BuscarZona", new object[] {
                        pLetra,
                        pAbrev}, this.BuscarZonaOperationCompleted, userState);
        }
        
        private void OnBuscarZonaOperationCompleted(object arg) {
            if ((this.BuscarZonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarZonaCompleted(this, new BuscarZonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Zona[] Listo() {
            object[] results = this.Invoke("Listo", new object[0]);
            return ((Zona[])(results[0]));
        }
        
        /// <remarks/>
        public void ListoAsync() {
            this.ListoAsync(null);
        }
        
        /// <remarks/>
        public void ListoAsync(object userState) {
            if ((this.ListoOperationCompleted == null)) {
                this.ListoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListoOperationCompleted);
            }
            this.InvokeAsync("Listo", new object[0], this.ListoOperationCompleted, userState);
        }
        
        private void OnListoOperationCompleted(object arg) {
            if ((this.ListoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListoCompleted(this, new ListoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListoPorDpto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Zona[] ListoPorDpto(string pLetraDpto) {
            object[] results = this.Invoke("ListoPorDpto", new object[] {
                        pLetraDpto});
            return ((Zona[])(results[0]));
        }
        
        /// <remarks/>
        public void ListoPorDptoAsync(string pLetraDpto) {
            this.ListoPorDptoAsync(pLetraDpto, null);
        }
        
        /// <remarks/>
        public void ListoPorDptoAsync(string pLetraDpto, object userState) {
            if ((this.ListoPorDptoOperationCompleted == null)) {
                this.ListoPorDptoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListoPorDptoOperationCompleted);
            }
            this.InvokeAsync("ListoPorDpto", new object[] {
                        pLetraDpto}, this.ListoPorDptoOperationCompleted, userState);
        }
        
        private void OnListoPorDptoOperationCompleted(object arg) {
            if ((this.ListoPorDptoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListoPorDptoCompleted(this, new ListoPorDptoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarEmpleado(Empleado E) {
            this.Invoke("AgregarEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void AgregarEmpleadoAsync(Empleado E) {
            this.AgregarEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void AgregarEmpleadoAsync(Empleado E, object userState) {
            if ((this.AgregarEmpleadoOperationCompleted == null)) {
                this.AgregarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("AgregarEmpleado", new object[] {
                        E}, this.AgregarEmpleadoOperationCompleted, userState);
        }
        
        private void OnAgregarEmpleadoOperationCompleted(object arg) {
            if ((this.AgregarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarEmpleado(Empleado E) {
            this.Invoke("EliminarEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void EliminarEmpleadoAsync(Empleado E) {
            this.EliminarEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void EliminarEmpleadoAsync(Empleado E, object userState) {
            if ((this.EliminarEmpleadoOperationCompleted == null)) {
                this.EliminarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("EliminarEmpleado", new object[] {
                        E}, this.EliminarEmpleadoOperationCompleted, userState);
        }
        
        private void OnEliminarEmpleadoOperationCompleted(object arg) {
            if ((this.EliminarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarEmpleado(Empleado E) {
            this.Invoke("ModificarEmpleado", new object[] {
                        E});
        }
        
        /// <remarks/>
        public void ModificarEmpleadoAsync(Empleado E) {
            this.ModificarEmpleadoAsync(E, null);
        }
        
        /// <remarks/>
        public void ModificarEmpleadoAsync(Empleado E, object userState) {
            if ((this.ModificarEmpleadoOperationCompleted == null)) {
                this.ModificarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("ModificarEmpleado", new object[] {
                        E}, this.ModificarEmpleadoOperationCompleted, userState);
        }
        
        private void OnModificarEmpleadoOperationCompleted(object arg) {
            if ((this.ModificarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado BuscarEmpleado(string pNomUsu) {
            object[] results = this.Invoke("BuscarEmpleado", new object[] {
                        pNomUsu});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEmpleadoAsync(string pNomUsu) {
            this.BuscarEmpleadoAsync(pNomUsu, null);
        }
        
        /// <remarks/>
        public void BuscarEmpleadoAsync(string pNomUsu, object userState) {
            if ((this.BuscarEmpleadoOperationCompleted == null)) {
                this.BuscarEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEmpleadoOperationCompleted);
            }
            this.InvokeAsync("BuscarEmpleado", new object[] {
                        pNomUsu}, this.BuscarEmpleadoOperationCompleted, userState);
        }
        
        private void OnBuscarEmpleadoOperationCompleted(object arg) {
            if ((this.BuscarEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEmpleadoCompleted(this, new BuscarEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarVisitas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Visita[] ListarVisitas() {
            object[] results = this.Invoke("ListarVisitas", new object[0]);
            return ((Visita[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarVisitasAsync() {
            this.ListarVisitasAsync(null);
        }
        
        /// <remarks/>
        public void ListarVisitasAsync(object userState) {
            if ((this.ListarVisitasOperationCompleted == null)) {
                this.ListarVisitasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarVisitasOperationCompleted);
            }
            this.InvokeAsync("ListarVisitas", new object[0], this.ListarVisitasOperationCompleted, userState);
        }
        
        private void OnListarVisitasOperationCompleted(object arg) {
            if ((this.ListarVisitasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarVisitasCompleted(this, new ListarVisitasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Casa : Propiedad {
        
        private bool fondoField;
        
        private decimal mt2TerrenoField;
        
        /// <comentarios/>
        public bool Fondo {
            get {
                return this.fondoField;
            }
            set {
                this.fondoField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Mt2Terreno {
            get {
                return this.mt2TerrenoField;
            }
            set {
                this.mt2TerrenoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Apto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Comercio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Casa))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Propiedad {
        
        private Empleado ultimoEmpField;
        
        private Zona zonaField;
        
        private decimal mt2ConstField;
        
        private int habitacionesField;
        
        private int bañoField;
        
        private string accionField;
        
        private int precioField;
        
        private string direccionField;
        
        private int padronField;
        
        /// <comentarios/>
        public Empleado UltimoEmp {
            get {
                return this.ultimoEmpField;
            }
            set {
                this.ultimoEmpField = value;
            }
        }
        
        /// <comentarios/>
        public Zona Zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Mt2Const {
            get {
                return this.mt2ConstField;
            }
            set {
                this.mt2ConstField = value;
            }
        }
        
        /// <comentarios/>
        public int Habitaciones {
            get {
                return this.habitacionesField;
            }
            set {
                this.habitacionesField = value;
            }
        }
        
        /// <comentarios/>
        public int Baño {
            get {
                return this.bañoField;
            }
            set {
                this.bañoField = value;
            }
        }
        
        /// <comentarios/>
        public string Accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
            }
        }
        
        /// <comentarios/>
        public int Precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        public int Padron {
            get {
                return this.padronField;
            }
            set {
                this.padronField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado {
        
        private string passField;
        
        private string nomUsuField;
        
        /// <comentarios/>
        public string Pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
            }
        }
        
        /// <comentarios/>
        public string NomUsu {
            get {
                return this.nomUsuField;
            }
            set {
                this.nomUsuField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Visita {
        
        private Propiedad aVisitarField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private System.DateTime fechaField;
        
        private int idField;
        
        /// <comentarios/>
        public Propiedad AVisitar {
            get {
                return this.aVisitarField;
            }
            set {
                this.aVisitarField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servicio {
        
        private string serviciosField;
        
        /// <comentarios/>
        public string Servicios {
            get {
                return this.serviciosField;
            }
            set {
                this.serviciosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Zona {
        
        private Servicio[] losServiciosField;
        
        private int cantHabitantesField;
        
        private string nombreField;
        
        private string abreviacionField;
        
        private string letraDptoField;
        
        /// <comentarios/>
        public Servicio[] LosServicios {
            get {
                return this.losServiciosField;
            }
            set {
                this.losServiciosField = value;
            }
        }
        
        /// <comentarios/>
        public int CantHabitantes {
            get {
                return this.cantHabitantesField;
            }
            set {
                this.cantHabitantesField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Abreviacion {
            get {
                return this.abreviacionField;
            }
            set {
                this.abreviacionField = value;
            }
        }
        
        /// <comentarios/>
        public string LetraDpto {
            get {
                return this.letraDptoField;
            }
            set {
                this.letraDptoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Apto : Propiedad {
        
        private bool ascensorField;
        
        private int pisoField;
        
        /// <comentarios/>
        public bool Ascensor {
            get {
                return this.ascensorField;
            }
            set {
                this.ascensorField = value;
            }
        }
        
        /// <comentarios/>
        public int Piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Comercio : Propiedad {
        
        private bool habilitadoField;
        
        /// <comentarios/>
        public bool Habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                this.habilitadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ParaPoderSerializarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AltaPropiedadCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BajaPropiedadCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ModificaPropiedadCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BuscarPropiedadCompletedEventHandler(object sender, BuscarPropiedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarPropiedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarPropiedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Propiedad Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Propiedad)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ParaPoderSerializarCAsaCompletedEventHandler(object sender, ParaPoderSerializarCAsaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParaPoderSerializarCAsaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParaPoderSerializarCAsaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Casa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Casa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ParaPoderSerializarAptoCompletedEventHandler(object sender, ParaPoderSerializarAptoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParaPoderSerializarAptoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParaPoderSerializarAptoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Apto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Apto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ParaPoderSerializarComercioCompletedEventHandler(object sender, ParaPoderSerializarComercioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParaPoderSerializarComercioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParaPoderSerializarComercioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Comercio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Comercio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListarPropiedadesCompletedEventHandler(object sender, ListarPropiedadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPropiedadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPropiedadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Propiedad[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Propiedad[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AgregarZonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void EliminarZonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ModificarZonaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BuscarZonaCompletedEventHandler(object sender, BuscarZonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarZonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarZonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zona Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zona)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListoCompletedEventHandler(object sender, ListoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zona[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zona[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListoPorDptoCompletedEventHandler(object sender, ListoPorDptoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListoPorDptoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListoPorDptoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zona[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zona[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AgregarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void EliminarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ModificarEmpleadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void BuscarEmpleadoCompletedEventHandler(object sender, BuscarEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ListarVisitasCompletedEventHandler(object sender, ListarVisitasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarVisitasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarVisitasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Visita[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Visita[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591